/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMAND = 9;
  /** RegularExpression Id. */
  int CAKETYPE = 10;
  /** RegularExpression Id. */
  int KEYWORD = 11;
  /** RegularExpression Id. */
  int STRUCTKEYWORD = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int NUM = 15;
  /** RegularExpression Id. */
  int COLOR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "\"DEFINE\"",
    "<CAKETYPE>",
    "<KEYWORD>",
    "\"LAYER\"",
    "<STRING>",
    "<CHAR>",
    "<NUM>",
    "<COLOR>",
    "\"=\"",
  };

}
