/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMAND = 11;
  /** RegularExpression Id. */
  int CAKETYPE = 12;
  /** RegularExpression Id. */
  int KEYWORD = 13;
  /** RegularExpression Id. */
  int STRUCTKEYWORD = 14;
  /** RegularExpression Id. */
  int LAYERPOSITION = 15;
  /** RegularExpression Id. */
  int LAYERHASCREAM = 16;
  /** RegularExpression Id. */
  int LAYERINGREDIENT = 17;
  /** RegularExpression Id. */
  int LAYERDIAMETER = 18;
  /** RegularExpression Id. */
  int LAYERATTR = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int NUM = 22;
  /** RegularExpression Id. */
  int COLOR = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"DEFINE\"",
    "<CAKETYPE>",
    "<KEYWORD>",
    "\"LAYER\"",
    "\"POSITION\"",
    "\"HASCREAM\"",
    "\"INGREDIENT\"",
    "\"DIAMETER\"",
    "<LAYERATTR>",
    "<STRING>",
    "<CHAR>",
    "<NUM>",
    "<COLOR>",
    "\"=\"",
    "\",\"",
  };

}
